name: Node.js Package Publisher

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Run integration test
        env:
          VALYU_API_KEY: ${{ secrets.VALYU_API_KEY }}
        run: node tests/integration-test.js

      - name: Publish to npm
        if: success() # Only publish if build and tests succeed
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 